version: "3.8"

services:
  flask:
    build: .
    container_name: flask_app
    env_file: .env
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - .:/app
      - ./logs:/app/logs  # ✅ Mount logs folder
    depends_on:
      - rabbit
    command: flask run --host=0.0.0.0 --port=${FLASK_PORT}
    restart: always

  celery:
    build: .
    container_name: celery_worker
    env_file: .env
    command: celery -A services.categorization_service.categorizer worker --loglevel=info
    depends_on:
      - rabbit
    volumes:
      - .:/app
      - ./logs:/app/logs 
    restart: always

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    restart: always
